# Generated by Django 3.0.6 on 2020-06-01 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0001_initial'),
        ('colegio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciudad.Ciudad'),
        ),
    ]
